apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: debenstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Projects Relevent to Ben and Personal Items
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/debenstack/debenstack-profile.git
    - https://github.com/debenstack/debenstack-techblog.git
    - https://github.com/debenstack/debenstack-personalblog.git
    - https://github.com/debenstack/debenstack-wiki.git
