apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projectterris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Projects with Business Potential
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/debenstack/debenstack-adventurewiki.git
    
