apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: profile
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: profile
  project: debenstack
  source:
    path: helm
    repoURL: https://github.com/debenstack/debenstack-profile.git
    targetRevision: master
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
