# All Values: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml

addPrometheusAnnotations: true

crds:
  install: true
  keep: true

#global:
#  domain: 

# Disable external authentication options
dex:
  enabled: false

# Disable notifications
notifications:
  enabled: false


applicationSet:
  enabled: false



  

controller:
  metrics:
    enabled: true
    applicationLabels:
      enabled: true
    serviceMonitor:
      enabled: true

redis:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

server: 
  extraArgs:
  # Run without HTTPS so that we can handle it at ingress
    - --insecure
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

repoServer:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true




