# All Values: https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
crds:
  enabled: true # whether to install the CRDs
  keep: true # whether to keep the CRDs after cert-manager is removed