additionalArguments: []
#  - --entrypoints.websecure.http.tls.certresolver=cloudflare
#  - --entrypoints.websecure.http.tls.domains[0].main=k8.projectterris.com
#  - --entrypoints.websecure.http.tls.domains[0].sans=*.k8.projectterris.com
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
#  - --certificatesresolvers.cloudflare.acme.email=ben@soernet.ca
#  - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
#  - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
# ^ All of these can be defined as values in this file! 
# Defaults: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

ports:
  web:
    redirectTo:
      port: websecure

#env:
#  - name: CF_API_EMAIL
#    valueFrom:
#      secretKeyRef:
#        key: email
#        name: cloudflare-api-credentials
#  - name: CF_API_KEY
#    valueFrom:
#      secretKeyRef:
#        key: apiKey
#        name: cloudflare-api-credentials

ingressRoute:
  dashboard:
    enabled: true

persistence:
  enabled: false
  path: /certs
  size: 128Mi