name: terraform-sec-check

# Only trigger, when the build workflow succeeded
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
      
permissions: read-all

jobs:
  tfsec-checks:
      runs-on: ubuntu-latest
      steps:
    
     # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v2
      
      # Tfsec - Security scanner for your Terraform code
      - name: Run Tfsec
        uses: aquasecurity/tfsec-action@v1.0.0